### ISSUE TITLE
README.md improvements

### ISSUE THREAD

**Issue by hanoba** [BenRoe/MMM-FHEM#5]
The table with configuration options is corrupted. 
Usage of "Font Awesome" should be added to "config.js" example file.

I have attached a README.md where both issues are fixed.

[README.md.zip](https://github.com/BenRoe/MMM-FHEM/files/924136/README.md.zip)

**Comment by BenRoe** [comment]
Oh thanks havent seen it. Why not do a pull request for the readme?

**Comment by hanoba** [comment]
I have now created a pull request.
